/**
 * Comprehensive SEO keyword library for Rahmat Ullah's portfolio.
 * Organized into thematic clusters for targeted page-level SEO.
 * These cover: name searches, technology searches, service intent, location, and project-based queries.
 */

// ─── IDENTITY & NAME KEYWORDS ────────────────────────────────────────────────
export const nameKeywords = [
  "Rahmat Ullah",
  "Rahmat Ullah developer",
  "Rahmat Ullah full stack developer",
  "Rahmat Ullah MERN developer",
  "Rahmat Ullah Next.js developer",
  "Rahmat Ullah React developer",
  "Rahmat Ullah Node.js developer",
  "Rahmat Ullah software developer",
  "Rahmat Ullah web developer",
  "Rahmat Ullah portfolio",
  "Rahmat Ullah Pakistan developer",
  "Rahmat Ullah Rawalpindi developer",
  "Rahmat Ullah JavaScript developer",
  "Rahmat Ullah TypeScript developer",
  "Rahmat Ullah MongoDB developer",
  "Rahmat Ullah PostgreSQL developer",
  "Rahmat Ullah React Native developer",
  "Rahmat Ullah AI developer",
  "Rahmat Ullah hire",
  "Rahmat Ullah freelance developer",
  "Rahmat Ullah backend developer",
  "Rahmat Ullah frontend developer",
  "Rahmat Ullah programmer",
  "Rahmat Ullah software engineer",
  "Rahmat Ullah engineer portfolio",
  "Rahmat baheer developer",
  "baheer224 developer",
];

// ─── FULL STACK DEVELOPER KEYWORDS ──────────────────────────────────────────
export const fullStackKeywords = [
  "full stack developer",
  "full stack web developer",
  "fullstack developer",
  "full stack JavaScript developer",
  "full stack TypeScript developer",
  "full stack Next.js developer",
  "full stack React developer",
  "full stack Node.js developer",
  "full stack MERN developer",
  "full stack developer portfolio",
  "full stack developer hire",
  "hire full stack developer",
  "experienced full stack developer",
  "professional full stack developer",
  "senior full stack developer",
  "remote full stack developer",
  "freelance full stack developer",
  "full stack developer Pakistan",
  "full stack developer Rawalpindi",
  "full stack developer for hire",
  "full stack web application developer",
  "full stack SaaS developer",
  "full stack API developer",
  "full stack developer with AI experience",
  "full stack developer with real-time apps",
  "full stack developer MongoDB",
  "full stack developer PostgreSQL",
  "full stack developer OpenAI",
  "full stack developer Stripe",
  "full stack developer Socket.IO",
];

// ─── MERN STACK KEYWORDS ─────────────────────────────────────────────────────
export const mernKeywords = [
  "MERN stack developer",
  "MERN developer",
  "MongoDB Express React Node developer",
  "MERN stack portfolio",
  "MERN stack web developer",
  "MERN stack full stack developer",
  "MERN stack developer hire",
  "hire MERN stack developer",
  "MERN developer Pakistan",
  "MERN developer for hire",
  "MERN stack developer remote",
  "professional MERN developer",
  "MERN stack application developer",
  "MERN stack SaaS developer",
  "MERN stack REST API developer",
  "MERN stack authentication",
  "MERN stack with Redux",
  "MERN stack with TypeScript",
  "MERN stack Next.js developer",
  "MERN stack real-time developer",
];

// ─── NEXT.JS KEYWORDS ────────────────────────────────────────────────────────
export const nextjsKeywords = [
  "Next.js developer",
  "Next.js full stack developer",
  "Next.js web developer",
  "Next.js App Router developer",
  "Next.js SSR developer",
  "Next.js SSG developer",
  "Next.js ISR developer",
  "Next.js Server Components developer",
  "Next.js API routes developer",
  "Next.js SEO developer",
  "Next.js performance optimization",
  "Next.js TypeScript developer",
  "Next.js Tailwind CSS developer",
  "Next.js MongoDB developer",
  "Next.js PostgreSQL developer",
  "Next.js authentication developer",
  "Next.js Stripe integration",
  "Next.js OpenAI integration",
  "Next.js real-time developer",
  "Next.js portfolio developer",
  "Next.js developer hire",
  "hire Next.js developer",
  "Next.js developer Pakistan",
  "Next.js developer remote",
  "Next.js freelance developer",
  "Next.js developer Vercel",
  "Next.js SaaS developer",
  "Next.js e-commerce developer",
  "Next.js dashboard developer",
  "Next.js production developer",
  "Next.js App Router full stack",
  "Next.js 15 developer",
  "Next.js 14 developer",
  "Next.js metadata API developer",
];

// ─── REACT KEYWORDS ──────────────────────────────────────────────────────────
export const reactKeywords = [
  "React developer",
  "React.js developer",
  "React full stack developer",
  "React frontend developer",
  "React web developer",
  "React developer hire",
  "hire React developer",
  "React Redux developer",
  "React Redux Toolkit developer",
  "React TypeScript developer",
  "React hooks developer",
  "React component developer",
  "React performance optimization",
  "React developer Pakistan",
  "React developer remote",
  "React developer for hire",
  "React SPA developer",
  "React dashboard developer",
  "React form developer",
  "React state management developer",
  "React context API developer",
  "React Tailwind CSS developer",
  "React Material UI developer",
  "React Ant Design developer",
  "React Shadcn developer",
  "React developer portfolio",
];

// ─── NODE.JS & BACKEND KEYWORDS ──────────────────────────────────────────────
export const nodejsKeywords = [
  "Node.js developer",
  "Node.js backend developer",
  "Node.js full stack developer",
  "Node.js Express developer",
  "Node.js API developer",
  "Node.js REST API developer",
  "Node.js developer hire",
  "hire Node.js developer",
  "Node.js developer Pakistan",
  "Node.js developer remote",
  "Node.js MongoDB developer",
  "Node.js PostgreSQL developer",
  "Node.js authentication developer",
  "Node.js JWT developer",
  "Node.js microservices developer",
  "Node.js scalable backend developer",
  "Express.js developer",
  "Express.js REST API developer",
  "Express.js middleware developer",
  "backend developer JavaScript",
  "backend developer Node.js",
  "backend API developer",
  "REST API developer",
  "RESTful API developer",
  "API developer for hire",
  "hire API developer",
  "backend developer hire",
  "backend developer Pakistan",
  "backend developer remote",
];

// ─── DATABASE KEYWORDS ───────────────────────────────────────────────────────
export const databaseKeywords = [
  "MongoDB developer",
  "MongoDB full stack developer",
  "MongoDB Node.js developer",
  "MongoDB schema design",
  "MongoDB aggregation developer",
  "MongoDB Atlas developer",
  "PostgreSQL developer",
  "PostgreSQL Node.js developer",
  "PostgreSQL full stack developer",
  "PostgreSQL database design",
  "SQL developer",
  "MySQL developer",
  "database developer",
  "database design developer",
  "NoSQL developer",
  "relational database developer",
  "MongoDB PostgreSQL developer",
  "full stack database developer",
  "database optimization developer",
];

// ─── JAVASCRIPT / TYPESCRIPT KEYWORDS ────────────────────────────────────────
export const jstsKeywords = [
  "JavaScript developer",
  "JavaScript full stack developer",
  "JavaScript web developer",
  "JavaScript developer hire",
  "TypeScript developer",
  "TypeScript full stack developer",
  "TypeScript React developer",
  "TypeScript Next.js developer",
  "TypeScript Node.js developer",
  "TypeScript developer hire",
  "ES6 developer",
  "modern JavaScript developer",
  "JavaScript developer Pakistan",
  "TypeScript developer Pakistan",
  "JavaScript developer portfolio",
  "TypeScript developer portfolio",
];

// ─── REACT NATIVE / MOBILE KEYWORDS ──────────────────────────────────────────
export const mobileKeywords = [
  "React Native developer",
  "React Native mobile developer",
  "React Native Expo developer",
  "React Native full stack developer",
  "React Native developer hire",
  "hire React Native developer",
  "cross-platform mobile developer",
  "iOS Android developer React Native",
  "mobile app developer JavaScript",
  "React Native developer Pakistan",
  "React Native developer remote",
  "Expo developer",
  "mobile app developer hire",
];

// ─── AI INTEGRATION KEYWORDS ─────────────────────────────────────────────────
export const aiKeywords = [
  "AI developer",
  "AI integration developer",
  "OpenAI developer",
  "OpenAI API developer",
  "OpenAI Next.js developer",
  "ChatGPT integration developer",
  "GPT-4 developer",
  "AI-powered web application developer",
  "AI SaaS developer",
  "AI web app developer",
  "machine learning API developer",
  "LLM integration developer",
  "AI prompt engineer developer",
  "AI full stack developer",
  "OpenAI integration hire",
  "hire AI developer",
  "AI developer Pakistan",
  "AI developer remote",
];

// ─── REAL-TIME KEYWORDS ───────────────────────────────────────────────────────
export const realTimeKeywords = [
  "real-time web developer",
  "Socket.IO developer",
  "WebSocket developer",
  "real-time chat developer",
  "real-time application developer",
  "live streaming developer",
  "Agora developer",
  "Zoom SDK developer",
  "video conferencing developer",
  "real-time dashboard developer",
  "Socket.IO Node.js developer",
  "real-time full stack developer",
  "live data streaming developer",
  "real-time notification developer",
  "WebRTC developer",
];

// ─── PAYMENT & STRIPE KEYWORDS ────────────────────────────────────────────────
export const paymentKeywords = [
  "Stripe developer",
  "Stripe integration developer",
  "Stripe payment developer",
  "Stripe subscription developer",
  "payment gateway developer",
  "e-commerce payment developer",
  "SaaS payment developer",
  "Stripe Next.js developer",
  "Stripe Node.js developer",
  "payment integration developer",
  "checkout developer",
];

// ─── SERVICE / HIRE INTENT KEYWORDS ──────────────────────────────────────────
export const hireKeywords = [
  "hire full stack developer",
  "hire Next.js developer",
  "hire React developer",
  "hire Node.js developer",
  "hire MERN developer",
  "hire JavaScript developer",
  "hire TypeScript developer",
  "hire MongoDB developer",
  "hire PostgreSQL developer",
  "hire React Native developer",
  "hire AI developer",
  "hire web developer",
  "hire backend developer",
  "hire frontend developer",
  "hire software developer",
  "hire software engineer",
  "freelance Next.js developer",
  "freelance React developer",
  "freelance full stack developer",
  "freelance MERN developer",
  "freelance Node.js developer",
  "freelance web developer",
  "freelance developer Pakistan",
  "remote Next.js developer",
  "remote React developer",
  "remote full stack developer",
  "remote MERN developer",
  "remote software developer",
  "remote JavaScript developer",
  "remote developer for hire",
  "contract developer",
  "contract full stack developer",
  "contract React developer",
  "contract Node.js developer",
  "web developer for hire",
  "developer for startup",
  "developer for SaaS product",
  "developer for e-commerce",
  "developer for mobile app",
  "developer for web application",
];

// ─── LOCATION-BASED KEYWORDS ─────────────────────────────────────────────────
export const locationKeywords = [
  "developer Pakistan",
  "web developer Pakistan",
  "full stack developer Pakistan",
  "MERN developer Pakistan",
  "Next.js developer Pakistan",
  "React developer Pakistan",
  "Node.js developer Pakistan",
  "JavaScript developer Pakistan",
  "developer Rawalpindi",
  "web developer Rawalpindi",
  "software developer Rawalpindi",
  "developer Islamabad",
  "web developer Islamabad",
  "Pakistani developer",
  "Pakistani full stack developer",
  "Pakistani software engineer",
  "developer KPK",
  "developer Peshawar",
  "remote developer from Pakistan",
  "Pakistan software developer portfolio",
];

// ─── TECHNOLOGY STACK KEYWORDS ────────────────────────────────────────────────
export const techStackKeywords = [
  "Tailwind CSS developer",
  "Shadcn UI developer",
  "Material UI developer",
  "Ant Design developer",
  "Redux developer",
  "Redux Toolkit developer",
  "Pinia developer",
  "Vue.js developer",
  "Vuex developer",
  "NextAuth.js developer",
  "JWT authentication developer",
  "Vercel deployment developer",
  "CI/CD developer",
  "Git developer",
  "GitHub developer",
  "REST API developer",
  "API integration developer",
  "web application developer",
  "SaaS developer",
  "dashboard developer",
  "admin panel developer",
  "e-commerce developer",
  "marketplace developer",
  "hospital management developer",
  "inventory management developer",
  "fleet management developer",
  "real estate app developer",
  "IoT web developer",
  "fintech developer",
];

// ─── BLOG & CONTENT KEYWORDS ─────────────────────────────────────────────────
export const blogKeywords = [
  "Next.js tutorial",
  "React tutorial",
  "Node.js tutorial",
  "TypeScript tutorial",
  "MongoDB tutorial",
  "PostgreSQL tutorial",
  "Socket.IO tutorial",
  "OpenAI API tutorial",
  "Next.js App Router guide",
  "Next.js SEO guide",
  "React Server Components guide",
  "Node.js REST API guide",
  "JWT authentication guide",
  "Next.js performance optimization",
  "React performance optimization",
  "full stack development guide",
  "MERN stack tutorial",
  "web development blog",
  "JavaScript blog",
  "developer blog",
  "Next.js developer blog",
  "React developer blog",
  "full stack developer blog",
];

// ─── COMPLETE SITE KEYWORDS (all combined, deduplicated) ─────────────────────
export const allSiteKeywords = [
  ...nameKeywords,
  ...fullStackKeywords,
  ...mernKeywords,
  ...nextjsKeywords,
  ...reactKeywords,
  ...nodejsKeywords,
  ...databaseKeywords,
  ...jstsKeywords,
  ...mobileKeywords,
  ...aiKeywords,
  ...realTimeKeywords,
  ...paymentKeywords,
  ...hireKeywords,
  ...locationKeywords,
  ...techStackKeywords,
].filter((v, i, a) => a.indexOf(v) === i); // deduplicate

// ─── PAGE-SPECIFIC KEYWORD SETS ──────────────────────────────────────────────
export const homePageKeywords = [
  ...nameKeywords,
  ...fullStackKeywords.slice(0, 15),
  ...mernKeywords.slice(0, 10),
  ...nextjsKeywords.slice(0, 15),
  ...reactKeywords.slice(0, 10),
  ...nodejsKeywords.slice(0, 10),
  ...hireKeywords.slice(0, 15),
  ...locationKeywords.slice(0, 10),
].filter((v, i, a) => a.indexOf(v) === i);

export const aboutPageKeywords = [
  ...nameKeywords,
  ...fullStackKeywords.slice(0, 10),
  ...mernKeywords.slice(0, 8),
  ...locationKeywords,
  "full stack developer background",
  "developer experience",
  "developer profile",
  "software developer about",
  "developer biography",
  "Rahmat Ullah about",
  "Rahmat Ullah background",
  "Rahmat Ullah career",
].filter((v, i, a) => a.indexOf(v) === i);

export const experiencePageKeywords = [
  ...nameKeywords.slice(0, 10),
  ...fullStackKeywords.slice(0, 8),
  "developer work history",
  "developer experience timeline",
  "professional developer experience",
  "Must Services developer",
  "M Techub developer",
  "Alphinex Solutions developer",
  "WQ Softwares developer",
  "NausalTech developer",
  "KPITB developer",
  "full stack developer career",
  "developer job history",
].filter((v, i, a) => a.indexOf(v) === i);

export const skillsPageKeywords = [
  ...nextjsKeywords.slice(0, 12),
  ...reactKeywords.slice(0, 12),
  ...nodejsKeywords.slice(0, 12),
  ...databaseKeywords,
  ...jstsKeywords,
  ...mobileKeywords.slice(0, 8),
  ...aiKeywords.slice(0, 8),
  ...realTimeKeywords.slice(0, 8),
  ...paymentKeywords.slice(0, 6),
  ...techStackKeywords,
  "developer skills",
  "programming skills",
  "technical skills developer",
].filter((v, i, a) => a.indexOf(v) === i);

export const projectsPageKeywords = [
  ...nameKeywords.slice(0, 10),
  ...fullStackKeywords.slice(0, 10),
  "developer portfolio projects",
  "full stack developer portfolio",
  "Next.js project examples",
  "React project portfolio",
  "MERN stack projects",
  "Node.js project examples",
  "web application examples",
  "CareerBooster AI",
  "MCare hospital management",
  "Oferta marketplace",
  "real-time web app examples",
  "AI web app examples",
  "e-commerce developer portfolio",
  "SaaS developer portfolio",
].filter((v, i, a) => a.indexOf(v) === i);

export const servicesPageKeywords = [
  ...hireKeywords,
  ...nextjsKeywords.slice(0, 12),
  ...reactKeywords.slice(0, 10),
  ...nodejsKeywords.slice(0, 10),
  ...mobileKeywords.slice(0, 8),
  ...aiKeywords.slice(0, 8),
  ...realTimeKeywords.slice(0, 6),
  ...paymentKeywords,
  "web development services",
  "full stack development services",
  "software development services",
  "React development services",
  "Next.js development services",
  "API development services",
  "mobile app development services",
  "AI integration services",
].filter((v, i, a) => a.indexOf(v) === i);

export const contactPageKeywords = [
  ...hireKeywords,
  ...nameKeywords.slice(0, 8),
  ...locationKeywords,
  "contact developer",
  "hire developer now",
  "developer inquiry",
  "project inquiry",
  "developer availability",
  "developer for startup",
  "developer for business",
  "get developer quote",
].filter((v, i, a) => a.indexOf(v) === i);

export const blogPageKeywords = [
  ...blogKeywords,
  ...nextjsKeywords.slice(0, 10),
  ...reactKeywords.slice(0, 8),
  ...nodejsKeywords.slice(0, 8),
  "web development tutorials",
  "JavaScript tutorials",
  "TypeScript tutorials",
  "developer insights",
  "programming articles",
  "tech blog",
  "developer blog Next.js",
].filter((v, i, a) => a.indexOf(v) === i);
